import type {Metadata} from "next";
import {Fraunces, Kulim_Park} from "next/font/google";
import "./globals.sass";
import clsx from "clsx";
import {NextFontWithVariable} from "next/dist/compiled/@next/font";

const kulimPark = Kulim_Park({
    weight: "400",
    variable: "--font-kulim-park",
    subsets: ["latin"],
});

const francues = Fraunces({
    variable: "--font-fraunces",
    subsets: ["latin"],
});

const fonts: NextFontWithVariable[] = [
    kulimPark,
    francues,
];

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={
                clsx(
                    `h-full antialiased`,
                    ...fonts.map(font => font.variable)
                )
            }
        >
        <body className={"flex flex-col"}>{children}</body>
        </html>
    );
}
